version: '3.1'
services:

  # The mongo serveice is for the database
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - my-network
    ports:
      - 27017:27017
    volumes:
      - mdb:/data/db

  # The mongo-express service is for the database management
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - my-network
  
  # The app service is for python development
  app:
    entrypoint:
      - sleep
      - infinity
    build: .
    init: true
    networks:
      - my-network


networks:
  my-network:
    

volumes:
  mdb: